web/appointment/urls.py
from django.urls import path
from . import views

app_name = 'appointment'

urlpatterns = [
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('appointment/', views.appointment, name='appointment'),
]

web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('appointment/', include('appointment.urls', namespace='appointment')),
]

web/appointment/models.py
from django.db import models
from django.core.validators import MinLengthValidator

from core.models import BaseModel


class Customer(BaseModel):
    """顧客"""
    name = models.CharField('名前', max_length=50)
    phone_number = models.CharField('電話番号', validators=[MinLengthValidator(10)], max_length=12)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "customer"
        verbose_name_plural = "顧客"
        unique_together = ["name", "phone_number"]


class Car(BaseModel):
    """車"""
    name = models.CharField('名前', max_length=255)
    number = models.CharField('ナンバープレート4桁', validators=[MinLengthValidator(4)], max_length=4)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)

    def __str__(self):
        return "{}/{}（{}）".format(self.name, self.number, self.customer.name)

    class Meta:
        db_table = "car"
        verbose_name_plural = "車"


class Appointment(BaseModel):
    """来店予約"""
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    visit_at = models.DateTimeField("予約日時")

    def __str__(self):
        return "{}（{}）".format(self.customer.name, self.visit_at)

    class Meta:
        db_table = "appointment"
        verbose_name_plural = "来店予約"

web/core/models.py
from django.db import models


class UndeletedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(deleted_at__isnull=True)


class BaseModel(models.Model):
    """ベースモデル"""
    created_at = models.DateTimeField('作成日時', auto_now_add=True)
    updated_at = models.DateTimeField('更新日時', auto_now=True)
    deleted_at = models.DateTimeField('論理削除日', blank=True, null=True)

    objects = UndeletedManager()
    all_objects = models.Manager()

    class Meta:
        abstract = True

web/appointment/forms.py
import re

from datetime import datetime

from django import forms
from django.core.exceptions import MultipleObjectsReturned, ObjectDoesNotExist

from appointment.models import Appointment, Customer


class AppointmentForm(forms.Form):
    visit_date = forms.DateField(
        label="日付",
        input_formats=['%Y/%m/%d'],
        widget=forms.TextInput(
            attrs={
                'class': 'form-control datetimepicker-input',
                'data-target': '#date-picker',
                'placeholder': 'YYYY/mm/dd',
            }
        )
    )
    visit_time = forms.TimeField(
        label="時刻",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control datetimepicker-input',
                'data-target': '#time-picker',
                'placeholder': 'HH:MM',
            }
        )
    )

    def __init__(self, customer_id: int, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.customer_id = customer_id

    def clean(self):
        now = datetime.now()
        if Appointment.objects.filter(customer_id=self.customer_id, visit_at__gte=now).exists():
            self.add_error(None, '既に予約されています。')

        cleaned_data = self.cleaned_data
        visit_date = cleaned_data['visit_date']
        visit_time = cleaned_data['visit_time']
        visit_at = datetime.combine(visit_date, visit_time)
        if Appointment.objects.filter(customer_id=self.customer_id, visit_at__gte=visit_at).exists():
            self.add_error(None, '現在日時より前に予約しています。')

        return visit_at


class LoginForm(forms.Form):
    name = forms.CharField(label="お名前", max_length=50)
    phone_number = forms.CharField(label="電話番号", help_text="数字のみ；ハイフン不可", min_length=10, max_length=12)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['phone_number'].widget.attrs['aria-describedby'] = 'phoneNumberHelp'
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control mt-1'

    def clean(self):
        """
        is_valid() is True ---> Customerインスタンスを返す
        is_valid() is False ---> cleaned_dataを返す
        """
        cleaned_data = self.cleaned_data
        name = cleaned_data['name']
        phone_number = cleaned_data['phone_number']
        try:
            customer = Customer.objects.get(name=name, phone_number=phone_number)
            return customer.id
        except ObjectDoesNotExist:
            self.add_error('phone_number', 'お名前もしくは電話番号が間違っています。')
        except MultipleObjectsReturned:
            self.add_error('phone_number', 'ご入力いただいたユーザー情報が複数見つかりました。\nお手数ですが担当者にご連絡ください。')
        return cleaned_data

web/appointment/views.py
import datetime

from django.contrib import messages
from django.http import HttpResponse
from django.views.decorators.http import require_GET, require_POST
from django.shortcuts import redirect, render

from appointment.forms import AppointmentForm, LoginForm
from appointment.models import Car, Customer, Appointment
from core.decorators import login_required, require_GET_POST


@require_GET_POST
def login(request):
    """ログイン"""
    if request.session.get('customer_id'):
        return redirect('appointment:appointment')
    form = LoginForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            request.session["customer_id"] = form.cleaned_data
            return redirect('appointment:appointment')

    return render(request, 'appointment/login.html', {'form': form})


@login_required
@require_GET_POST
def logout(request):
    """ログアウト"""
    if request.session.get('customer_id'):
        del request.session["customer_id"]
    return redirect('appointment:login')


@login_required
@require_GET_POST
def appointment(request):
    """来店予約"""
    form = AppointmentForm(request.customer.id, request.POST or None)
    # form = 'form'
    if request.method == "POST":
        if form.is_valid():
            Appointment.objects.create(
                customer=request.customer,
                visit_at=form.cleaned_data,
            )
            return HttpResponse('OK')

    return render(request, 'appointment/appointment.html', {'form': form})

web/templates/appointment/appointment.html
{% extends 'appointment/base.html' %}
{% load static %}

{% block title%}ログイン{% endblock%}

{% block style %}
<style type="text/css">
.datepicker-days th.dow:first-child,
.datepicker-days td:first-child {
  color: #f00;
}
.datepicker-days th.dow:last-child,
.datepicker-days td:last-child {
  color: #00f;
}
</style>
{% endblock %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <div class="card">
        <div class="card-header">
        
        </div>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <p class="text-danger">
              <i class="fas fa-exclamation-triangle pe-2"></i>{{ error }}
            </p>
            {% endfor %}
            
            <span>{{ form.visit_date.label_tag }}</span>
            <div class="input-group date mb-3" id="date-picker" data-target-input="nearest">
              {{ form.visit_date }}{{ form.visit_date.errors }}
              <div class="input-group-text" data-target="#date-picker" data-toggle="datetimepicker">
                <i class="far fa-calendar-alt"></i>
              </div>
            </div>
            
            <span>{{ form.visit_time.label_tag }}</span>
            <div class="input-group date mb-3" id="time-picker" data-target-input="nearest">
              {{ form.visit_time }}{{ form.visit_time.errors }}
              <div class="input-group-text" data-target="#time-picker" data-toggle="datetimepicker">
                <i class="far fa-clock"></i>
              </div>
            </div>
            
            <div class="d-grid gap-2">
              <button class="btn btn-primary" type="submit">送信</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>






{% endblock%}

{% block script %}
<script type="text/javascript">
$(function() {
  $('#date-picker').datetimepicker({
  dayViewHeaderFormat: 'YYYY年 MMMM',
  tooltips: {
      close: '閉じる',
      selectMonth: '月を選択',
      prevMonth: '前月',
      nextMonth: '次月',
      selectYear: '年を選択',
      prevYear: '前年',
      nextYear: '次年',
      selectTime: '時間を選択',
      selectDate: '日付を選択',
      prevDecade: '前期間',
      nextDecade: '次期間',
      selectDecade: '期間を選択',
      prevCentury: '前世紀',
      nextCentury: '次世紀',
    },
  timepicker: false,
  format: 'YYYY/MM/DD',
  locale: 'ja',
  icons: {
      time: 'far fa-clock',
      date: 'far fa-calendar-alt',
      up: 'fas fa-arrow-up',
      down: 'fas fa-arrow-down',
    },
    buttons: {
      showClose: true,
    },
  });
  
  
  $('#time-picker').datetimepicker({
    tooltips: {
      close: '閉じる',
      pickHour: '時間を取得',
      incrementHour: '時間を増加',
      decrementHour: '時間を減少',
      pickMinute: '分を取得',
      incrementMinute: '分を増加',
      decrementMinute: '分を減少',
      pickSecond: '秒を取得',
      incrementSecond: '秒を増加',
      decrementSecond: '秒を減少',
      togglePeriod: '午前/午後切替',
      selectTime: '時間を選択',
    },
    datepicker: false,
    format: 'HH:mm',
    locale: 'ja',
    icons: {
      time: 'far fa-clock',
      date: 'far fa-calendar-alt',
      up: 'fas fa-arrow-up',
      down: 'fas fa-arrow-down',
    },
    buttons: {
      showClose: true,
    },
  });
  
  
});

</script>
{% endblock %}

web/templates/appointment/base.html
{% extends 'base.html' %}
{% load static %}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="">ご来店予約</a>
    <div class="d-flex">
      {% if request.customer %}
      <span class="navbar-text me-3">{{ request.customer }} 様</span>
      <button class="btn btn-secondary btn-sm" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">ログアウト
      </button>
      {% else %}
      <span class="navbar-text">ログイン</span>
      {% endif %}
    </div>
  </div>
</nav>

<!-- ログアウトボタン押下時の確認用モーダル -->
<div class="modal" id="exampleModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">ご確認</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>ログアウトしますか？</p>
      </div>
      <div class="modal-footer">
        <form id="deleteForm" method="post" action="{% url 'appointment:logout' %}">{% csrf_token %}</form>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">いいえ</button>
        <button form="deleteForm" class="btn btn-primary">ログアウト</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

web/templates/appointment/login.html
{% extends 'appointment/base.html' %}
{% load static %}

{% block title%}ログイン{% endblock%}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <div class="card">
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            <div class="mb-3">
              {{ form.name.label_tag }}
              {{ form.name }}
              {{ form.name.error }}
            </div>
            <div class="mb-3">
              {{ form.phone_number.label_tag }}
              {{ form.phone_number }}
              <div id="phoneNumberHelp" class="form-text">{{ form.phone_number.help_text }}</div>
              {{ form.phone_number.errors }}
            </div>
            <div class="d-grid gap-2">
              <button class="btn btn-primary" type="submit">送信</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock%}

web/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %}</title>
  
  <!-- Bootstrap CSS -->
  <link href="{% static 'plugin/bootstrap-5.0.2-dist/css/bootstrap.min.css' %}" rel="stylesheet">
  
  <!-- Font Awesome CSS -->
  <link rel="stylesheet" href="{% static 'plugin/fontawesome-free-5.15.3-web/css/all.css' %}">
  
  <!-- datetimepicker CSS -->
  <link href="{% static 'plugin/Bootstrap-4-Date-Time-Picker/build/css/tempusdominus-bootstrap-4.css' %}" rel="stylesheet">
  
  {% block style %}{% endblock %}

</head>

<body>
  {% block navbar %}{% endblock %}
  {% block content %}{% endblock %}

  <!-- jQuery -->
  <script src="{% static 'plugin/jQuery/jquery-3.6.0.min.js' %}"></script>
  
  <!-- Bootstrap JS -->
  <script src="{% static 'plugin/bootstrap-5.0.2-dist/js/bootstrap.min.js' %}"></script>
  
  <!-- datetimepicker for bootstrap4 JS -->
  <script src="{% static 'plugin/Customizable Date & Time Picker For Bootstrap 4/moment-with-locales.min.js' %}"></script>
  
  <!-- datetimepicker JS -->
  <script src="{% static 'plugin/Bootstrap-4-Date-Time-Picker/build/js/tempusdominus-bootstrap-4.js' %}"></script>
{% block script %} {% endblock %}
</body>
</html>